project_k/project_k/urls.py
from django.contrib import admin
from django.urls import path, include
from report.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", index, name='index'),
    path("object_kes/<int:id>/", object_kes, name='object_kes'),
    path("area/<int:id>/", area, name='area'),
    path("dgu_settings/<int:id>/", dgu_settings, name='dgu_settings'),
    path("dgu/<int:id>/", dgu, name='dgu'),
    path("create_dgu/", create_dgu, name='create_dgu'),
    path("create_report/<int:id>/", create_report, name='create_report'),
    path("edit_report/<int:id>/", edit_report, name='edit_report'),
    path("edit_dgu/<int:id>/", edit_dgu, name='edit_dgu'),
    path("delete_dgu/<int:id>/", delete_dgu, name='delete_dgu'),
    path('users/', include('users.urls', namespace="users")),
]

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "Комплексные Энерго-Системы"

project_k/users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
]

project_k/report/views.py
from datetime import date
from django.contrib.auth.decorators import login_required
from django.shortcuts import render

from .models import CreateDGU, ReportDGU, ObjectKES, Location
from django.http import HttpResponseRedirect, HttpResponseNotFound, HttpResponse



@login_required
def index(request):
    dgus = CreateDGU.objects.all()
    location = Location.objects.all()
    object_kes = ObjectKES.objects.filter(public=True,)
    return render(request, "index.html", {'dgus': dgus, 'location': location, 'object_kes': object_kes})

@login_required
def create_report(request, id):
    dgu_name = CreateDGU.objects.get(id=id)
    name = dgu_name.name
    def chec_zpt(text):
        return text.replace(',', '.') if ',' in text else text

    try:
        lct = dgu_name.location.id
        alter = dgu_name.alternator.hours_alternator
        if request.method == "POST":
            report = ReportDGU()
            report.dgu_id = id
            report.author = request.user
            mot_hours = float(chec_zpt(request.POST.get("narabotka")))
            report.narabotka = str(mot_hours)
            nar = mot_hours - dgu_name.hours
            report.nar = str(nar)
            dgu_name.alternator.hours_alternator = dgu_name.alternator.hours_alternator + nar
            dgu_name.alternator.save(update_fields=["hours_alternator"])
            dgu_name.dvs.engine_hours = dgu_name.dvs.engine_hours + nar
            dgu_name.dvs.save(update_fields=["engine_hours"])
            dgu_name.hours = mot_hours
            dgu_name.save(update_fields=["hours"])
            report.nagruzka = request.POST.get("nagruzka")
            report.active = request.POST.get("active")
            report.reactive = request.POST.get("reactive")
            report.full_load = request.POST.get("full_load")
            report.l1 = request.POST.get("l1")
            report.l2 = request.POST.get("l2")
            report.l3 = request.POST.get("l3")
            report.total_power = request.POST.get("total_power")
            report.voltage = request.POST.get("voltage")
            report.frequency = request.POST.get("frequency")
            report.dmasla = chec_zpt(request.POST.get("dmasla"))
            report.tc = chec_zpt(request.POST.get("tc"))
            report.akb = chec_zpt(request.POST.get("akb"))
            # Топливо
            report.emkost_nak = dgu_name.emkost_nak
            report.emkost_nak_pok = request.POST.get("emkost_nak")
            report.emkost_pit = dgu_name.emkost_pit
            report.emkost_pit_pok = request.POST.get("emkost_pit")
            report.pump_meter = dgu_name.pump_meter
            report.pump_meter_pok = request.POST.get("pump_meter")

            report.mercury_pok = request.POST.get("mercury")
            report.title = request.POST.get("title")

            report.save()
            return HttpResponseRedirect(f"/area/{lct}")
        else:
            return render(request, "create_report.html", {"name": name, 'lct': lct, "dgu_name": dgu_name, "alter": alter,})
    except Exception as exc:
        iskl = exc.__class__.__name__
        return render(request, "create_report.html", {"name": name, 'iskl': iskl})

@login_required
def create_dgu(request):


    if request.method == "POST":
        dgu = CreateDGU()
        dgu.name = request.POST.get("name")
        dgu.title = request.POST.get("title")
        dgu.save()
        return HttpResponseRedirect("/")
    return render(request, "create_dgu.html", )

@login_required
def edit_dgu(request, id):
    try:
        dgu = CreateDGU.objects.get(id=id)
        if request.method == "POST":
            dgu.name = request.POST.get("name")
            dgu.title = request.POST.get("title")
            dgu.save()
            return HttpResponseRedirect("/")
        else:
            return render(request, "edit_dgu.html", {"dgu": dgu,})
    except :
        return HttpResponseNotFound("<h2>Product not found</h2>")

@login_required
def edit_report(request, id):
    def chec_zpt(text):
        return text.replace(',', '.') if ',' in text else text

    try:
        rpt = ReportDGU.objects.get(id=id)
        lct = rpt.dgu.location.id
        name = rpt.dgu.name
        time = rpt.time_create

        if request.method == "POST":
            rpt.narabotka = chec_zpt(request.POST.get("narabotka"))
            rpt.active = request.POST.get("active")
            rpt.save()
            return HttpResponseRedirect(f"/area/{lct}")
        else:
            return render(request, "edit_report.html", {"rpt": rpt,
                                                        "name": name, "time": time,})
    except :
        return HttpResponseNotFound("<h2>Product not found</h2>")


@login_required
def delete_dgu(request, id):
    try:
        dgu = CreateDGU.objects.get(id=id)
        dgu.delete()
        return HttpResponseRedirect("/")
    except:
        return HttpResponseNotFound("<h2>Product not found</h2>")

@login_required
def object_kes(request, id):
    dgus = CreateDGU.objects.all()
    location = Location.objects.filter(object_kes=id)
    object_kes = ObjectKES.objects.get(id=id)
    return render(request, "object_kes.html", {'dgus': dgus,
                                               'location': location, 'object_kes': object_kes})

@login_required
def area(request, id):
    y, m, d = (int(i) for i in date.today().isoformat().split("-"))
    dgus = CreateDGU.objects.filter(location=id)
    location = Location.objects.get(id=id)
    object_kes = Location.objects.get(id=id).object_kes.name
    report = ReportDGU.objects.filter(time_create__date=date(y, m, d), dgu__location__id=id)
    rpt = set(i.dgu.name for i in report)
    return render(request, "area.html",
                  {'dgus': dgus, 'location': location, 'object_kes': object_kes,
                   'report': report, 'rpt': rpt, 'dmy': (d, m, y)})

@login_required
def dgu_settings(request, id):
    try:
        dgu = CreateDGU.objects.get(id=id)
        if request.method == "POST":
            dgu.narabotka = (False if request.POST.get("narabotka") == None else True)
            dgu.nagruzka = (False if request.POST.get("nagruzka") == None else True)
            dgu.l1 = (False if request.POST.get("l1") == None else True)
            dgu.l2 = (False if request.POST.get("l2") == None else True)
            dgu.l3 = (False if request.POST.get("l3") == None else True)
            dgu.dmasla = (False if request.POST.get("dmasla") == None else True)
            dgu.tog = (False if request.POST.get("tog") == None else True)
            dgu.primechanie = (False if request.POST.get("primechanie") == None else True)
            dgu.save()
            return HttpResponseRedirect("../../")
        else:
            return render(request, "dgu_settings.html", {"dgu": dgu,})
    except :
        return HttpResponseNotFound("<h2>Product not found</h2>")

@login_required
def dgu(request, id):
    try:
        dgu = CreateDGU.objects.get(id=id)
        if request.method == "POST":
            dgu.name = request.POST.get("name")
            dgu.title = request.POST.get("title")
            dgu.save()
            return HttpResponseRedirect("../")
        else:
            return render(request, "dgu.html", {"dgu": dgu,})
    except :
        return HttpResponseNotFound("<h2>Product not found</h2>")

project_k/report/templates/1111.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
    <h3>Список ДГУ</h3>
    <table>
        <thead><th>Название</th><th>Описание</th><th></th></thead>
        {% for dgu in dgus %}
        <tr>
            <td>{{ dgu.name }}</td>
            <td>{{ dgu.title }}</td>
            <td>
                <a href="edit_dgu/{{dgu.id}}">Изменить</a> |
                <a href="delete_dgu/{{dgu.id}}">Удалить</a> |
                <a href="create_report/{{dgu.id}}">Отсчет</a> |
            </td>
        </tr>
        {% endfor %}
    </table>

    <a href="create_dgu/">Добавить ДГУ</a>

    <table>
        <thead><th>Проблема</th><th>Температура ДВС</th><th>ДГУ</th></thead>
        {% for report in report_dgu %}
        <tr>
            <td>{{ report.title}}</td>
            <td>{{ report.tc }}</td>
            <td>{{ report.dgu.name }}</td>

        </tr>
        {% endfor %}
    </table>
{% else %}
<p>необходима авторизация</p>
{% endif %}

{% endblock %}

project_k/report/templates/area.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Участок{% endblock title %}
{% block css %}
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <link rel="stylesheet" href="{% static 'style/style_area.css' %}">
{% endblock css %}

{% block content %}
<main>
    <p>{{ object_kes }}</p> <br>
    <p>{{ location.name }} {{ location.operator }}</p> <br>
        <div class="blok_1  inline">
            {% for dgu in dgus %}
                <table>
                    <tr>
                        {% if dgu.status.id == 2 %} <!-- Аварийная остановка -->
                            <td class="st1 dgu_status_avar"><a href="{% url 'dgu' dgu.id %}" >{{dgu.name}}</a></td>
                            <td class="st5 dgu_status_avar">{{dgu.dvs.engine_hours}}</td>
                            <td class="st2 dgu_status_avar">{{dgu.dvs.model_dvs.model_dvs}}</td>
                            <td class="st3 dgu_status_avar">Аварийная остановка</td>
                            <td class="st6 dgu_status_avar">{{dgu.title}}</td>
                            <td class="st4 dgu_status_avar"><a href="../../create_report/{{dgu.id}}">Ремонт</a></td>
                        {% elif  dgu.status.id == 3 %} <!-- Ремонт -->
                            <td class="st1 dgu_status_rem"><a href="{% url 'dgu' dgu.id %}" >{{dgu.name}}</a></td>
                            <td class="st5 dgu_status_rem">{{dgu.dvs.engine_hours}}</td>
                            <td class="st2 dgu_status_rem">{{dgu.dvs.model_dvs.model_dvs}}</td>
                            <td class="st3 dgu_status_rem">Ремонт</td>
                            <td class="st6 dgu_status_rem">{{dgu.title}}</td>
                            <td class="st4 dgu_status_rem"><a href="../../create_report/{{dgu.id}}">Ремонт</a></td>
                        {% elif not dgu.work %} <!-- Резерв -->
                            <td class="st1 dgu_status_res"><a href="{% url 'dgu' dgu.id %}" >{{dgu.name}}</a></td>
                            <td class="st5 dgu_status_res">{{dgu.dvs.engine_hours}}</td>
                            <td class="st2 dgu_status_res">{{dgu.dvs.model_dvs.model_dvs}}</td>
                                {% if dgu.status.id == 4 %}
                                    <td class="st3 dgu_status_rem">Требуется незн. ремонт</td>
                                {% elif dgu.status.id == 5 %}
                                    <td class="st3 dgu_status_avar">Требуется ТО</td>
                                {% else %}
                                    <td class="st3 dgu_status_res">Резерв</td>
                                {% endif %}
                            <td class="st6 dgu_status_res">{{dgu.title}}</td>
                            <td class="st4 dgu_status_res"><a href="../../create_report/{{dgu.id}}">Тест запуск</a></td>
                        {% elif dgu.work %} <!-- В работе -->
                            <td class="st1 dgu_status_rab" ><a href="{% url 'dgu' dgu.id %}" >{{dgu.name}}</a></td>
                            <td class="st5 dgu_status_rab">{{dgu.dvs.engine_hours}}</td>
                            <td class="st2 dgu_status_rab">{{dgu.dvs.model_dvs.model_dvs}}</td>
                                {% if dgu.status.id == 4 %}
                                    <td class="st3 dgu_status_rem">Требуется незн. ремонт</td>
                                {% elif dgu.status.id == 5 %}
                                    <td class="st3 dgu_status_avar">Требуется ТО</td>
                                {% else %}
                                    <td class="st3 dgu_status_rab">В Работе</td>
                                {% endif %}
                            <td class="st6 dgu_status_rab">{{dgu.title}}</td>
                            {% if dgu.name in rpt %}
                            <td class="st4 dgu_status_rab"><a href="../../create_report/{{dgu.id}}">Отчет</a></td>
                            {% else %}
                            <td class="st4 dgu_status_avar"><a href="../../create_report/{{dgu.id}}">Отчет</a></td>
                            {% endif %}
                        {% endif %}
                    </tr></table>
                {% endfor %}
            </div>
<img src="{% static  'img/0.gif'%}" class="zero">
    <table>
    {% for rpt in report %}
    <tr>
        <td>{{ rpt.author }}</td>
        <td>{{ rpt.time_create|time:"H:i" }}</td>
        <td>{{ rpt.narabotka }}</td>
        <td>{{ rpt.dgu.name }}</td>
        <td>{{ rpt.dgu.location }}</td>
    </tr>
    {% endfor %}</table>

<img src="{% static  'img/0.gif'%}" class="zero">
    <!-- Настраиваем отчет -->
<table>
    <caption><b>Ежедневный отчет от {{ dmy }}</b></caption>
    <thead>
        <tr>
            <th class="stl_01" >ДГУ</th>
            <th class="stl_01" >Время</th>
            <th class="stl_1" >М/Ч</th>
            <th class="stl_3" >Нагруз.</th>
            <th class="stl_4" >АктНагр</th>
            <th class="stl_5" >РеактН.</th>
            <th class="stl_6" >ПолнН.</th>
            <th class="stl_7" >L1</th>
            <th class="stl_8" >L2</th>
            <th class="stl_9" >L3</th>
            <th class="stl_10" >ОбщМощ</th>
            <th class="stl_11" >Напряж.</th>
            <th class="stl_12" >Частота</th>
            <th class="stl_13" >ДавлМасл</th>
            <th class="stl_13" >Темп.О.Ж</th>
        </tr>
    </thead>
    <tbody>
        {% for rpt in report %}
        <tr>
            <td>{{ rpt.dgu.name }}</td>
            <td>{{ rpt.time_create|time:"H:i" }}</td>
            <td>{{ rpt.narabotka }}</td>
            <td>{{ rpt.nagruzka }}</td>
            <td>{{ rpt.active }}</td>
            <td>{{ rpt.full_load }}</td>
            <td>{{ rpt.l1}}</td>
            <td>{{ rpt.l2}}</td>
            <td>{{ rpt.l3}}</td>
            <td>{{ rpt.total_power}}</td>
            <td>{{ rpt.voltage}}</td>
            <td>{{ rpt.frequency}}</td>
            <td>{{ rpt.dmasla}}</td>
            <td>{{ rpt.tc}}</td>
            <td>{{ rpt.akb}}</td>
        </tr>
    {% endfor %}
    </tbody>

</table>
<img src="{% static  'img/0.gif'%}" class="zero">
<table>
    <caption><b>Tопливный отчет от {{ dmy }}</b></caption>
        <tr>
            <td class="stl_01" >ДГУ</td>
            <td class="stl_14" >Наработкa</td>
            <td class="stl_02" >Время</td>
            <td class="stl_15" >ТКнакоп</td>
            <td class="stl_16" >Пок.см</td>
            <td class="stl_17" >Емк.пит.</td>
            <td class="stl_18" >Пок.см</td>
            <td class="stl_19" >Счетчик</td>
            <td class="stl_20" >Показан</td>
        </tr>
        {% for rpt in report %}
        <tr>
            <td class="stl_01" >{{ rpt.dgu.name }}</td>
            <td class="stl_14" >{{ rpt.nar }}</td>
            <td class="stl_02" >{{ rpt.time_create|time:"H:i" }}</td></th>
            <td class="stl_15" >{{ rpt.emkost_nak.number }}</td>
            <td class="stl_16" >{{ rpt.emkost_nak_pok }}</td>
            <td class="stl_17" >{{ rpt.emkost_pit.number }}</td>
            <td class="stl_18" >{{ rpt.emkost_pit_pok }}</td>
            <td class="stl_19" >{{ rpt.pump_meter.name }}</td>
            <td class="stl_20" >{{ rpt.pump_meter_pok }}</td>
        </tr>
        {% endfor %}
</table>
<img src="{% static  'img/0.gif'%}" class="zero">
            <!--             -->

</main>
{% endblock content %}

project_k/report/templates/base — копия.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}КЭС{% endblock title %}</title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'style/style.css' %}">
    {% endblock css %}
</head>
<body>
    
    <!-- Navigation bar -->
    <header class="header">
        <!-- Logo -->
         <a href="{%url 'index'%}" class="logo">
            <img src="{% static  'img/logo02.jpg' %}" width="35%" height="35%" alt="КЭС">
        </a>

        <!-- Hamburger icon -->
        <input class="side-menu" type="checkbox" id="side-menu"/>
        <label class="hamb" for="side-menu"><span class="hamb-line"></span></label>

        <!-- Menu -->
        <nav class="nav">
            <ul class="menu">
                {% if user.is_authenticated %}
                <li><a href="{%url 'create_dgu'%}">Отчет</a></li>
                <li><a href="#">About</a></li>

                <li><a href="admin/">{{user.username}}</a></li>
                <li><a href="{%url 'users:logout'%}">Выход</a></li>

                <li><a href="{%url 'users:logout'%}">{{user.username}} | Выход</a></li>

                {% else %}
                <li><a href="{%url 'users:login'%}">Авторизация</a></li>
                {% endif %}

            </ul>
        </nav>
    </header>

    <!-- Main content -->
    {% block content %}{% endblock content %}

</body>
</html>

project_k/report/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}КЭС{% endblock title %}</title>
    {% block css %}
        <link rel="stylesheet" href="{% static 'style/style.css' %}">
    {% endblock css %}
</head>
<body>
    
    <!-- Navigation bar -->
    <header class="header">
        <!-- Logo -->
         <a href="{%url 'index'%}" class="logo">КЭС</a>

        <!-- Hamburger icon -->
        <input class="side-menu" type="checkbox" id="side-menu"/>
        <label class="hamb" for="side-menu"><span class="hamb-line"></span></label>

        <!-- Menu -->
        <nav class="nav">
            <ul class="menu">
                {% if user.is_authenticated %}
                <li><a href="{%url 'create_dgu'%}">Отчет</a></li>
                <li><a href="#">About</a></li>

                <li><a href="admin/">{{user.username}}</a></li>
                <li><a href="{%url 'users:logout'%}">Выход</a></li>

                <li><a href="{%url 'users:logout'%}">{{user.username}} | Выход</a></li>

                {% else %}
                <li><a href="{%url 'users:login'%}">Авторизация</a></li>
                {% endif %}

            </ul>
        </nav>
    </header>

    <!-- Main content -->
    {% block content %}{% endblock content %}

</body>
</html>

project_k/report/templates/create_dgu.html
{% extends 'base.html' %}

{% block content %}
    <h2>Добавление ДГУ</h2>
    <form method="POST">
        {% csrf_token %}
        <p>
            <label>Название ДГУ</label><br>
            <input type="text" name="name" />
        </p>
        <p>
            <label>Описание</label><br>
            <input type="text" name="title" />
        </p>

        <input type="submit" value="Сохранить" >
    </form>
{% endblock %}

project_k/report/templates/create_report.html
{% extends 'base.html' %}

{% block content %}
<main>
	<p>  </p>
	<form method="POST">
    {% csrf_token %}
			<fieldset>
				<legend>Ввод Данных ДГУ № {{name}}  <p>{{ iskl }} </p> <br></legend>
				<br>
				<p>Моточасы: <input type="text" name = "narabotka" placeholder = "Введите моточасы"> м/ч </p><br> <br>

				{% if dgu_name.narabotka %}
					<p>Нагрузка: <input type="text" name = "nagruzka" placeholder = "Нагрузка"> кВт</p> <br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.active %}
					<p>Активная: <input type="text" name = "active" placeholder = "Активная Нагрузка"> кВт</p> <br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.reactive %}
					<p>Реактивная: <input type =  "text" name = "reactive" placeholder = "Реактивная  Нагрузка"> кВт</p> <br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.full_load %}
					<p>Полная: <input type =  "text" name = "full_load" placeholder = "Полная  Нагрузка"> кВт</p> <br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.l1 %}
				<p>L1:       <input type =  "text" name = "l1" placeholder = "L1"> A</p><br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.l2 %}
				<p>L2:       <input type =  "text" name = "l2" placeholder = "L2"> A</p><br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.l3 %}
					<p>L3:       <input type =  "text" name = "l3" placeholder = "L3"> A</p><br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.total_power %}
					<p>Полн.Мощность:       <input type =  "text" name = "total_power" placeholder = "Полная Мощьность"> A</p><br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.voltage %}
					<p>Напряжение:       <input type =  "text" name = "voltage" placeholder = "Напряжение"> В</p><br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.frequency %}
					<p>Частота:       <input type =  "text" name = "frequency" placeholder = "Частота"> </p><br> <br>
				{% else %}
				{% endif %}

				{% if dgu_name.dmasla %}
				<p>Дав.Масла:<input type =  "text" name = "dmasla" placeholder = "Давление Масла"> Кг/см²</p><br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.tog %}
					<p>Темп. ОЖ: <input type="text" name="tc" placeholder = "Температура Антифриза"> °C</p><br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.akb %}
					<p>АКБ: <input type="text" name="akb" placeholder = "Температура Антифриза"> V</p><br> <br>
				{% else %}
				{% endif %}
			<!-- Топливо	счетчики -->

				{% if dgu_name.tk_nak %}
					<p>ТК накоп {{ emkost_nak.number }} <input type="text" name="emkost_nak" placeholder = "Топливный контейнер"> см</p><br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.emk_pit %}
					<p>Емкость пит <input type="text" name="emkost_pit" placeholder = "Емкость питательная"> см</p><br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.pump_m %}
					<p>Счетчик Насоса <input type="text" name="pump_meter" placeholder = "Счетчик Насоса"> л</p><br> <br>
				{% else %}
				{% endif %}
				{% if dgu_name.mrc %}
					<p>Меркурий <input type="text" name="mercury" placeholder = "Меркурий"> </p><br> <br>
				{% else %}
				{% endif %}
				<p>Примечания:</p><p><textarea  name="title" rows="5" cols="35"> </textarea></p><br> <br>

				<input type = "submit" name = "submit" value = "отправить">
			</fieldset>
		</form>
        <p>
	        <label for="ffile">📷 Сделать фото/видео:</label>
	        <input type="file" id="ffile" capture="user" accept="audio/*, video/*" style="color:transparent;" onchange="this.style.color = 'black';"/>
        </p>
</main>

{% endblock %}

project_k/report/templates/dgu.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <p><a href="{% url 'dgu_settings' dgu.id %}" >Настройка отчета ДГУ № {{dgu.name}}</a></p>
{% endblock content %}

project_k/report/templates/dgu_settings.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <main>
	 <form method="POST">
            {% csrf_token %}
			<fieldset>
				<legend>Настройка отчета ДГУ № {{dgu.name}}</legend>
				<br>
				<p><input type="checkbox" checked name="narabotka"/>
						Наработка:<input type =  "number"  placeholder = "Введите моточасы">
					м/ч</p><br> <br>
				<p><input type="checkbox" checked name="nagruzka"/>
						Нагрузка: <input type =  "number"  placeholder = "Нагрузка">
					кВт</p> <br> <br>
				<p><input type="checkbox" checked name="l1"/>
					L1:       <input type =  "number" name = "" placeholder = "L1">
					A</p><br> <br>
				<p><input type="checkbox" checked name="l2"/>
					L2:       <input type =  "number"  placeholder = "L2">
					A</p><br> <br>
				<p><input type="checkbox" checked name="l3"/>
					L3:       <input type =  "number"  placeholder = "L3">
					A</p><br> <br>
				<p><input type="checkbox" checked name="dmasla"/>
					Дав.Масла:<input type =  "number"  placeholder = "Давление Масла">
					Кг/см²</p><br> <br>
				<p><input type="checkbox" checked name="tog"/>
					Темп. ОЖ: <input type =  "number"  placeholder = "Температура Антифриза">
					°C
				</p><br> <br>
				<p><input type="checkbox" checked name="primechanie"/>
					Примечания:<input type =  "text"  placeholder = "Примечания">
				</p><br> <br>


				<input type = "submit" name = "submit" value = "Сохранить">
			</fieldset>
		</form>
    </main>
{% endblock content %}

project_k/report/templates/edit_dgu.html
{% extends 'base.html' %}
{% block title %}Изменить Отчет{% endblock title %}

{% block content %}
    <h2>Изменение товара</h2>
    <form method="POST">
        {% csrf_token %}
        <p>
            <label>Изменить название ДГУ</label><br>
            <input type="text" name="name" value="{{dgu.name}}" />
        </p>
        <p>
            <label>Изменить мощьность</label><br>
            <input type="number" name="title" value="{{dgu.title}}"/>
        </p>

        <input type="submit" value="Сохранить" >
    </form>
{% endblock %}

project_k/report/templates/edit_report.html
{% extends 'base.html' %}
{% block title %}Изменить Отчет{% endblock title %}

{% block content %}
<main>
	<p>  </p>
	<form method="POST">
    {% csrf_token %}
		<fieldset>
			<legend>Изменить Отчет ДГУ № {{name}}  <p>от {{ time }} </p> <br></legend>
				<br>
			<p>
            <label>Изменить Наработка</label><br>
            	<input type="text" name="narabotka" value="{{rpt.narabotka}}" />
        	</p>
        	<p>
            <label>Изменить Активная нагрузка</label><br>
            	<input type="text" name="active" value="{{rpt.active}}"/>
        	</p>

        <input type="submit" value="Сохранить" >
        </fieldset>
    </form>
</main>
{% endblock %}